### PR TITLE
feat: handle multiple files

### PR DESCRIPTION
**Pull request by HiromiShikata**
Hi @kahirokunn,

Thank you for your useful npm package! :+1:
deepmerge-yaml is really nice for me to merge my circleci configs for each services on my monoricic repository.

I want to use it for multiple files, so please review this PR :bow:
Please give me any feedback :bow:

### CODE REVIEW

**Review by kahirokunn — APPROVED** [review]
LGTM!

**Comment by kahirokunn** [comment]
Thanks for the PR! I would release early 👍

**Comment by kahirokunn** [comment]
https://www.npmjs.com/package/deepmerge-yaml

released 0.0.2

**Comment by HiromiShikata** [comment]
@kahirokunn 
Great🙌, Thank you very much!!🙇

**Pull request merged**
